### PR TITLE
Admin wrap css

### PR DESCRIPTION
**Pull request by soft79**
Hi,

The wp-multilang css `#wpbody-content .wrap` interferes when meta boxes contain a .wrap element. For example WooCommerce > Product > Shipping > Dimensions.

This pull request fixes it by removing some css. This results into the language switcher position being relative instead of absolute. 

If you don't agree with the PR (you probably made the language switcher absolute for a reason) another option would be changing the css selector to `#wpbody-content > .wrap`

### CODE REVIEW

**Comment by VaLeXaR** [comment]
Hi @soft79 .
Not all plugins have .wrap as child of #wpbody-content. That is why I made it relative.

**Comment by soft79** [comment]
Hi, would it be possible to change it to `#wpbody-content > .wrap` then?

**Comment by VaLeXaR** [comment]
@soft79 after what? Or you mean add styles on js?

**Comment by soft79** [comment]
Hi, I meant the css-selector in includes/admin/class-wpm-admin-assets.php . Please, see updated PR.

**Comment by VaLeXaR** [comment]
I've done so earlier. Okay, I'll do it again. But I need to review this option. Perhaps there is a better solution.

**Comment by soft79** [comment]
Probably, I'm by no means a css expert.

**Pull request merged**
