### PR TITLE
Make sure ACF Gutenberg Blocks render properly with wysiwyg, text and…

### PR DESCRIPTION
**Pull request by damircalusic**
… textarea

### CODE REVIEW

**Comment by Anticosti** [comment]
@damircalusic Big Thanks for this fix. Hope Valexar will update soon. Are you able to reach him?
Please join our FB group:
https://www.facebook.com/groups/wpmultilang.users/

**Comment by damircalusic** [comment]
No problem @Anticosti :) I cannot reach him. I have made several bug fixes on my projects and it would be awesome if someone could push them out!

**Comment by ciribeli** [comment]
I need a help, i used the new solution but create other problem, the additional camp what not have in the block dont work

**Comment by damircalusic** [comment]
> I need a help, i used the new solution but create other problem, the additional camp what not have in the block dont work

Hi @ciribeli, I dont know what problems you have exactly but I detected a bug with ACF options pages and made an fix with this commit https://github.com/VaLeXaR/wp-multilang/pull/182/commits/9ec27b4e59abcf5857e9dd0898b28b2b5b8c6357

Maybe it will help you aswell.

**Pull request closed without merging**
