### PR TITLE
Fallback if translation is not found

### PR DESCRIPTION
**Pull request by soft79**
If both the translation to the requested language and the default language are not found, fallback to the first available translation.

### CODE REVIEW

**Comment by VaLeXaR** [comment]
I do not think it is necessary. You can get lost in translations. I already thought to do this, but I decided to leave, as it is now.

**Comment by soft79** [comment]
I understand. 

In my case I use it because we have a WooCommerce store; and many of the product titles are only entered in 1 language, but not always the default language (depends on the store manager). It would be really useful in this case. 

But I could solve this another way, so no problem...

**Comment by VaLeXaR** [comment]
I will add filter for this in next version. Now it is in develop branch.

**Comment by soft79** [comment]
Very nice solution, thanks.

**Pull request closed without merging**
